# Cổng backend
server.port=8080

# Cấu hình kết nối CSDL
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FinancialManagement;encrypt=true;trustServerCertificate=true;instanceName=SQLEXPRESS
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
